### ISSUE TITLE
Several Plugins all have ST3 support

### ISSUE THREAD

**Issue by joeybaker** [SublimeGit/CanISwitchToSublimeText3#4]
- https://github.com/randy3k/AlignTab
- https://github.com/randy3k/AutoWrap
- https://github.com/eproxus/focus_last_tab
- https://github.com/compleatang/sublimetext-pastepdf
- https://github.com/jbrooksuk/StripHTML

**Comment by miped** [comment]
Updated. Thank you for reporting them.

**Comment by joeybaker** [comment]
Cheers – thanks!
