### ISSUE TITLE
two plugins incorrectly listed as "not working"

### ISSUE THREAD

**Issue by joeybaker** [SublimeGit/CanISwitchToSublimeText3#6]
https://github.com/unphased/SublimeStatusbarPath

https://bitbucket.org/hmml/jsonlint

**Comment by miped** [comment]
Hi Joey,

I'm no longer "in charge" of the data as it comes directly from Package Control 2. In that data, they are both marked as not working with sublime text 3, which means you won't be able to install them using Package Control on ST3.

Please file individual tickets with the respective authors.

**Comment by joeybaker** [comment]
Whoops sorry about that — thanks
