### ISSUE TITLE
Packages marked as not possible sometimes are.

### ISSUE THREAD

**Issue by GrantSP** [SublimeGit/CanISwitchToSublimeText3#7]
Not actually an issue as such, probably a case of keeping up with changes. Nevertheless 2 of my version 2 packages can successfully be installed in version 3.

Namely:
Find++
Lua Dev

Jumped too soon.

Although Find ++ CAN be installed, it appears to have no functionality. Oops.

**Comment by miped** [comment]
I haven't run an update in a while. I'll be sure to update it this weekend, and get some cron set up.

**Comment by miped** [comment]
These 2 packages are now marked as st3 ready after a quick data update.
